### ISSUE TITLE
Non-directory links trigger stacktraces instead of proper errors

### ISSUE THREAD

**Issue by TicClick** [Walavouchey/osu-wiki-tools#16]
https://github.com/ppy/osu-wiki/actions/runs/4223273375/jobs/7332811480

```
wiki/Beatmap/Pattern/Mania/Anchors/en.md:7:50: Mania/Streams
wiki/Beatmap/Pattern/Mania/Anchors/en.md:7:88: Mania/Jacks/en.md#chordjacks
Note: "/wiki/Beatmap/Pattern/Mania/Anchors/Mania/Streams" was not found 
Note: "/wiki/Beatmap/Pattern/Mania/Anchors/Mania/Jacks/en.md" was not found
```

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.2/x64/bin/osu-wiki-tools", line 8, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools_cli/osu_wiki_tools.py", line 77, in console_main
    sys.exit(main(*sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools_cli/osu_wiki_tools.py", line 73, in main
    return parsed_args.func(*subcommand_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools_cli/commands/check_links.py", line 103, in main
    errors = link_checker.check_article(a, redirects, articles)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools/link_checker.py", line 128, in check_article
    local_errors = [
                   ^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools/link_checker.py", line 128, in <listcomp>
    local_errors = [
                   ^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools/link_checker.py", line 130, in <genexpr>
    check_link(article, link, redirects, article.references, all_articles)
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools/link_checker.py", line 97, in check_link
    all_articles[raw_path] = article_parser.parse(target_file)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools/article_parser.py", line 140, in parse
    with path.open('r', encoding='utf-8') as fd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: 'wiki/Beatmap/Pattern/Mania/Jacks/en.md/en.md'
```

**Comment by TicClick** [comment]
the exact link was: `Mania/Jacks/en.md#chordjacks`, and then the checker just crashed

**Comment by TicClick** [comment]
```
2023-03-23T18:22:04.6613411Z [36;1mosu-wiki-tools check-links --target "${WIKILINK_TARGET_FILES[@]}"[0m
2023-03-23T18:22:04.6670544Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2023-03-23T18:22:04.6670815Z env:
2023-03-23T18:22:04.6671835Z   INTERESTING_FILES: .gitignore
wiki/Guides/Common_modding_mistakes/en.md
wiki/People/Beatmap_Nominators/Becoming_a_Beatmap_Nominator/en.md
wiki/People/Beatmap_Nominators/Becoming_a_Beatmap_Nominator/es.md
wiki/People/Beatmap_Nominators/Becoming_a_Beatmap_Nominator/fr.md
wiki/People/Beatmap_Nominators/Becoming_a_Beatmap_Nominator/ru.md
wiki/People/Beatmap_Nominators/Becoming_a_Beatmap_Nominator/tr.md
wiki/People/Beatmap_Nominators/Becoming_a_Beatmap_Nominator/zh.md
wiki/People/Nomination_Assessment_Team/Evaluations/en.md
wiki/People/Nomination_Assessment_Team/Evaluations/fr.md
wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator/img/ApplicationFlowchart.png
2023-03-23T18:22:04.6672926Z   pythonLocation: /opt/hostedtoolcache/Python/3.11.2/x64
2023-03-23T18:22:04.6673280Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.2/x64/lib/pkgconfig
2023-03-23T18:22:04.6673633Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.2/x64
2023-03-23T18:22:04.6673960Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.2/x64
2023-03-23T18:22:04.6674281Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.2/x64
2023-03-23T18:22:04.6674613Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.2/x64/lib
2023-03-23T18:22:04.6674921Z   PULL_REQUEST_TAG: SKIP_WIKILINK_CHECK
2023-03-23T18:22:04.6675168Z ##[endgroup]
2023-03-23T18:22:04.8008835Z Traceback (most recent call last):
2023-03-23T18:22:04.8010094Z   File "/opt/hostedtoolcache/Python/3.11.2/x64/bin/osu-wiki-tools", line 8, in <module>
2023-03-23T18:22:04.8011053Z     sys.exit(console_main())
2023-03-23T18:22:04.8011744Z              ^^^^^^^^^^^^^^
2023-03-23T18:22:04.8012829Z   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools_cli/osu_wiki_tools.py", line 77, in console_main
2023-03-23T18:22:04.8013259Z     sys.exit(main(*sys.argv[1:]))
2023-03-23T18:22:04.8013533Z              ^^^^^^^^^^^^^^^^^^^
2023-03-23T18:22:04.8017070Z   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools_cli/osu_wiki_tools.py", line 73, in main
2023-03-23T18:22:04.8019546Z     return parsed_args.func(*subcommand_args)
2023-03-23T18:22:04.8021361Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-23T18:22:04.8022470Z   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools_cli/commands/check_links.py", line 103, in main
2023-03-23T18:22:04.8025208Z     errors = link_checker.check_article(a, redirects, articles)
2023-03-23T18:22:04.8027159Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-23T18:22:04.8027896Z   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools/link_checker.py", line 128, in check_article
2023-03-23T18:22:04.8030284Z     local_errors = [
2023-03-23T18:22:04.8030801Z                    ^
2023-03-23T18:22:04.8031659Z   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools/link_checker.py", line 128, in <listcomp>
2023-03-23T18:22:04.8036630Z     local_errors = [
2023-03-23T18:22:04.8037618Z                    ^
2023-03-23T18:22:04.8038548Z   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools/link_checker.py", line 130, in <genexpr>
2023-03-23T18:22:04.8039100Z     check_link(article, link, redirects, article.references, all_articles)
2023-03-23T18:22:04.8039838Z   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools/link_checker.py", line 97, in check_link
2023-03-23T18:22:04.8040340Z     all_articles[raw_path] = article_parser.parse(target_file)
2023-03-23T18:22:04.8041122Z                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-23T18:22:04.8042284Z   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/wikitools/article_parser.py", line 140, in parse
2023-03-23T18:22:04.8042833Z     with path.open('r', encoding='utf-8') as fd:
2023-03-23T18:22:04.8043157Z          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-23T18:22:04.8043917Z   File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/pathlib.py", line 1044, in open
2023-03-23T18:22:04.8053536Z     return io.open(self, mode, buffering, encoding, errors, newline)
2023-03-23T18:22:04.8053917Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-23T18:22:04.8054719Z FileNotFoundError: [Errno 2] No such file or directory: 'wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator/en.md'
2023-03-23T18:22:04.8186636Z ##[error]Process completed with exit code 1.
```

via https://github.com/ppy/osu-wiki/actions/runs/4503929362/jobs/7927753885 (the links were anything under `/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator`, where `The_Team` was removed in https://github.com/ppy/osu-wiki/pull/9000)
